test build
https://github.com/yeesian/ArchGDAL.jl/pull/315#issuecomment-1210903206

```
ERROR: LoadError: LoadError: InitError: could not load library "/Users/runner/.julia/artifacts/525a7050baaa2b0732225f4528525dfb3cfed1df/lib/libproj.25.dylib"
dlopen(/Users/runner/.julia/artifacts/525a7050baaa2b0732225f4528525dfb3cfed1df/lib/libproj.25.dylib, 1): Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /Users/runner/.julia/artifacts/525a7050baaa2b0732225f4528525dfb3cfed1df/lib/libproj.25.9.0.1.dylib
  Reason: Incompatible library version: libproj.25.dylib requires version 13.0.0 or later, but libcurl.4.dylib provides version 12.0.0
```